// AUTO-GENERATED by process-images.mjs - fleet and experience metadata.
export type Vehicle = { slug: string; name: string; category: string };
export const FLEET: Vehicle[] = [
  {
    "slug": "porsche-cayenne",
    "name": "Porsche Cayenne Turbo GT",
    "category": "Luxury"
  },
  {
    "slug": "range-rover-sport",
    "name": "Range Rover Sport",
    "category": "Luxury"
  },
  {
    "slug": "ford-mustang",
    "name": "Ford Mustang Convertible",
    "category": "Sport"
  },
  {
    "slug": "jeep-cherokee",
    "name": "Jeep Cherokee",
    "category": "SUV"
  },
  {
    "slug": "toyota-highlander",
    "name": "Toyota Highlander",
    "category": "SUV"
  },
  {
    "slug": "honda-crv",
    "name": "Honda CR-V",
    "category": "SUV"
  },
  {
    "slug": "hyundai-santa-fe",
    "name": "Hyundai Santa Fe",
    "category": "SUV"
  },
  {
    "slug": "ford-explorer",
    "name": "Ford Explorer",
    "category": "SUV"
  },
  {
    "slug": "changan-cs55",
    "name": "Changan CS55 Plus",
    "category": "SUV"
  },
  {
    "slug": "toyota-camry",
    "name": "Toyota Camry",
    "category": "Sedan"
  },
  {
    "slug": "kia-k5",
    "name": "Kia K5",
    "category": "Sedan"
  },
  {
    "slug": "toyota-yaris",
    "name": "Toyota Yaris",
    "category": "Economy"
  },
  {
    "slug": "hyundai-grand-i10",
    "name": "Hyundai Grand i10",
    "category": "Economy"
  }
];
export const CATEGORIES = ["All", "Luxury", "Sport", "SUV", "Sedan", "Economy"] as const;
